from dotenv import load_dotenv
import os

load_dotenv()

# تنظیمات API تلگرام
API_ID = int(os.getenv("API_ID") or 0)  # اگر API_ID توی .env نباشه، 0 می‌ذاره
API_HASH = os.getenv("API_HASH") or ""  # اگر API_HASH توی .env نباشه، خالی می‌ذاره
PHONE = os.getenv("PHONE") or ""  # اگر PHONE توی .env نباشه، خالی می‌ذاره
CREATOR_ID = int(os.getenv("CREATOR_ID") or 0)  # اگر CREATOR_ID توی .env نباشه، 0 می‌ذاره
MASTER_PASSWORD = os.getenv("MASTER_PASSWORD") or ""  # اگر MASTER_PASSWORD توی .env نباشه، خالی می‌ذاره

# بررسی مقادیر ضروری
if not API_ID or not API_HASH or not PHONE or not CREATOR_ID or not MASTER_PASSWORD:
    raise ValueError("لطفاً مقادیر API_ID، API_HASH، PHONE، CREATOR_ID و MASTER_PASSWORD رو توی فایل .env وارد کنید!")

# متغیرهای گلوبال
USER_STATES = {}  # دیکشنری برای ذخیره وضعیت کاربران

# پیام‌های منو (چندزبانه)
MENU_TEXTS = {
    "fa": {
        "main_menu": ["مدیریت ادمین‌ها", "مدیریت کانال‌ها", "ترجمه متن", "توقف بات", "تنظیمات"],
        "welcome": "خوش اومدی! لطفاً از منو انتخاب کن:",
        "creator_init": "لطفاً کلمه رمز رو بفرست تا Creator ثبت بشی:",
        "creator_success": "شما به عنوان Creator ثبت شدید!",
        "not_admin": "شما ادمین نیستید!",
        "chat_destination": "لطفاً آیدی چت مقصد رو بفرست (مثلاً @username یا ID عددی):",
        "admins_menu": ["لیست ادمین‌ها", "اضافه کردن ادمین", "حذف ادمین", "ارتقا/تنزل ادمین", "بازگشت"],
        "channels_menu": ["لیست کانال‌ها", "اضافه کردن کانال", "حذف کانال", "لیست سیاه", "فیلتر کلمات", "لینک دعوت برای کانال خصوصی", "رد کردن کانال", "بازگشت"],
        "admin_list": "لیست ادمین‌ها:\n{list}",
        "add_admin_prompt": "در کدام سطح؟ مستر ادمین، سوپر ادمین یا ادمین:",
        "add_admin_id": "آیدی عددی ادمین رو بفرست:",
        "admin_added": "ادمین {user_id} در سطح {level} اضافه شد!",
        "remove_admin_id": "آیدی ادمین رو بفرست:",
        "admin_removed": "ادمین {user_id} حذف شد!",
        "promote_demote": "ادمین رو انتخاب کن:\n{list}\nسپس بگو 'ارتقا' یا 'تنزل':",
        "level_changed": "سطح {user_id} به {level} تغییر کرد!",
        "channels_list": "کانال‌های شما:\n{list}",
        "add_channel_prompt": "آیدی کانال یا پیام فورواردشده بفرست:",
        "channel_added": "کانال با موفقیت اضافه شد!",
        "remove_channel_prompt": "آیدی کانال رو بفرست:",
        "channel_removed": "کانال حذف شد!",
        "blacklist_prompt": "آیدی کانال برای لیست سیاه:",
        "blacklist_added": "کانال به لیست سیاه اضافه شد!",
        "blacklist_error": "این کانال در لیست سیاهه!",
        "limit_exceeded": "حداکثر تعداد کانال‌ها برای سطح شما: {limit}",
        "translate_prompt": "متن رو بفرست:",
        "stop_personal": "بات برای شما متوقف شد!",
        "stop_global": "بات برای همه متوقف شد!",
        "settings_menu": ["زبان اینترفیس", "زبان مقصد ترجمه", "تغییر چت مقصد", "قالب پیام دریافتی", "بازگشت"],
        "interface_lang": "زبان اینترفیس رو انتخاب کن (fa، en، ar، ru):",
        "dest_lang": "زبان مقصد ترجمه رو انتخاب کن (مثلاً en یا fr):",
        "no_access": "شما دسترسی به این کار ندارید!",
        "capacity_increased": "ظرفیت تعداد کانال‌های تحت رصد شما به {limit} افزایش یافت!",
        "channels_adjusted": "به دلیل تنزل سطح، {count} کانال آخر از لیست شما حذف شد.",
        "filter_menu": ["لیست سیاه کلمات", "لیست سفید کلمات", "بازگشت"],
        "select_channel": "کانال رو انتخاب کن:\n{list}",
        "blacklist_words": "کلمات لیست سیاه رو بفرست (با کاما جدا کن):",
        "whitelist_words": "کلمات لیست سفید رو بفرست (با کاما جدا کن):",
        "filter_added": "فیلتر برای {channel} ثبت شد!",
        "message_format": "قالب پیام رو انتخاب کن:\n1. فقط متن\n2. متن + کانال مبدا",
        "format_set": "قالب پیام به '{format}' تنظیم شد!",
        "back": "بازگشت",
        "stop_options": ["شخصی", "گلوبال", "بازگشت"],
        "error_numeric_id": "آیدی باید عدد باشه!",
        "error_invalid_format": "فرمت اشتباهه! مثلاً 'ID ارتقا' یا 'ID تنزل'",
        "error_invalid_channel": "کانال نامعتبر!",
        "error_invalid_lang": "فقط fa، en، ar، ru!",
        "error_invalid_format_choice": "فقط 1 یا 2!",
        "monitor_error": "خطا در نظارت بر کانال {channel}: {error}",
        "invite_link_prompt": "لینک دعوت کانال خصوصی رو بفرست (یا بنویس 'رد' برای رد کردن):",
        "invite_link_saved": "لینک دعوت ذخیره شد!",
        "channel_skipped": "کانال رد شد."
    },
    "en": {
        "main_menu": ["Manage Admins", "Manage Channels", "Translate Text", "Stop Bot", "Settings"],
        "welcome": "Welcome! Please choose from the menu:",
        "creator_init": "Please send the password to register as Creator:",
        "creator_success": "You are registered as Creator!",
        "not_admin": "You are not an admin!",
        "chat_destination": "Please send the destination chat ID (e.g., @username or numeric ID):",
        "admins_menu": ["List Admins", "Add Admin", "Remove Admin", "Promote/Demote Admin", "Back"],
        "channels_menu": ["List Channels", "Add Channel", "Remove Channel", "Blacklist", "Word Filters", "Invite Link for Private Channel", "Skip Channel", "Back"],
        "admin_list": "Admins list:\n{list}",
        "add_admin_prompt": "At which level? Master Admin, Super Admin, or Admin:",
        "add_admin_id": "Send the admin’s numeric ID:",
        "admin_added": "Admin {user_id} added at level {level}!",
        "remove_admin_id": "Send the admin’s ID:",
        "admin_removed": "Admin {user_id} removed!",
        "promote_demote": "Select an admin:\n{list}\nThen say 'Promote' or 'Demote':",
        "level_changed": "Level of {user_id} changed to {level}!",
        "channels_list": "Your channels:\n{list}",
        "add_channel_prompt": "Send channel ID or a forwarded message:",
        "channel_added": "Channel added successfully!",
        "remove_channel_prompt": "Send the channel ID:",
        "channel_removed": "Channel removed!",
        "blacklist_prompt": "Channel ID for blacklist:",
        "blacklist_added": "Channel added to blacklist!",
        "blacklist_error": "This channel is blacklisted!",
        "limit_exceeded": "Maximum number of channels for your level: {limit}",
        "translate_prompt": "Send the text:",
        "stop_personal": "Bot stopped for you!",
        "stop_global": "Bot stopped for everyone!",
        "settings_menu": ["Interface Language", "Translation Target Language", "Change Chat Destination", "Message Format", "Back"],
        "interface_lang": "Choose interface language (fa, en, ar, ru):",
        "dest_lang": "Choose translation target language (e.g., en or fr):",
        "no_access": "You don’t have access to this!",
        "capacity_increased": "Your channel monitoring capacity increased to {limit}!",
        "channels_adjusted": "Due to demotion, {count} last channels were removed from your list.",
        "filter_menu": ["Blacklist Words", "Whitelist Words", "Back"],
        "select_channel": "Select a channel:\n{list}",
        "blacklist_words": "Send blacklist words (comma-separated):",
        "whitelist_words": "Send whitelist words (comma-separated):",
        "filter_added": "Filter set for {channel}!",
        "message_format": "Choose message format:\n1. Text only\n2. Text + source channel",
        "format_set": "Message format set to '{format}'!",
        "back": "Back",
        "stop_options": ["Personal", "Global", "Back"],
        "error_numeric_id": "ID must be numeric!",
        "error_invalid_format": "Wrong format! E.g., 'ID Promote' or 'ID Demote'",
        "error_invalid_channel": "Invalid channel!",
        "error_invalid_lang": "Only fa, en, ar, ru!",
        "error_invalid_format_choice": "Only 1 or 2!",
        "monitor_error": "Error monitoring channel {channel}: {error}",
        "invite_link_prompt": "Send the invite link for the private channel (or type 'Skip' to skip):",
        "invite_link_saved": "Invite link saved!",
        "channel_skipped": "Channel skipped."
    },
    "ar": {
        "main_menu": ["إدارة المشرفين", "إدارة القنوات", "ترجمة النص", "إيقاف البوت", "الإعدادات"],
        "welcome": "مرحبًا! الرجاء الاختيار من القائمة:",
        "creator_init": "أرسل كلمة المرور للتسجيل كمنشئ:",
        "creator_success": "تم تسجيلك كمنشئ!",
        "not_admin": "أنت لست مشرفًا!",
        "chat_destination": "أرسل معرف الدردشة المقصودة (مثل @username أو ID رقمي):",
        "admins_menu": ["قائمة المشرفين", "إضافة مشرف", "حذف مشرف", "ترقية/تنزيل مشرف", "رجوع"],
        "channels_menu": ["قائمة القنوات", "إضافة قناة", "حذف قناة", "القائمة السوداء", "فلاتر الكلمات", "رابط دعوة لقناة خاصة", "تخطي القناة", "رجوع"],
        "admin_list": "قائمة المشرفين:\n{list}",
        "add_admin_prompt": "في أي مستوى؟ مشرف رئيسي، مشرف خارق، أو مشرف:",
        "add_admin_id": "أرسل معرف المشرف الرقمي:",
        "admin_added": "تمت إضافة المشرف {user_id} في المستوى {level}!",
        "remove_admin_id": "أرسل معرف المشرف:",
        "admin_removed": "تم حذف المشرف {user_id}!",
        "promote_demote": "اختر مشرفًا:\n{list}\nثم قل 'ترقية' أو 'تنزيل':",
        "level_changed": "تم تغيير مستوى {user_id} إلى {level}!",
        "channels_list": "قنواتك:\n{list}",
        "add_channel_prompt": "أرسل معرف القناة أو رسالة معاد توجيهها:",
        "channel_added": "تمت إضافة القناة بنجاح!",
        "remove_channel_prompt": "أرسل معرف القناة:",
        "channel_removed": "تم حذف القناة!",
        "blacklist_prompt": "معرف القناة للقائمة السوداء:",
        "blacklist_added": "تمت إضافة القناة إلى القائمة السوداء!",
        "blacklist_error": "هذه القناة في القائمة السوداء!",
        "limit_exceeded": "الحد الأقصى لعدد القنوات لمستواك: {limit}",
        "translate_prompt": "أرسل النص:",
        "stop_personal": "تم إيقاف البوت بالنسبة لك!",
        "stop_global": "تم إيقاف البوت للجميع!",
        "settings_menu": ["لغة الواجهة", "لغة الترجمة المستهدفة", "تغيير وجهة الدردشة", "تنسيق الرسالة", "رجوع"],
        "interface_lang": "اختر لغة الواجهة (fa، en، ar، ru):",
        "dest_lang": "اختر لغة الترجمة المستهدفة (مثل en أو fr):",
        "no_access": "ليس لديك صلاحية لهذا!",
        "capacity_increased": "تم زيادة سعة مراقبة القنوات الخاصة بك إلى {limit}!",
        "channels_adjusted": "بسبب التنزيل، تم حذف {count} قنوات أخيرة من قائمتك.",
        "filter_menu": ["كلمات القائمة السوداء", "كلمات القائمة البيضاء", "رجوع"],
        "select_channel": "اختر قناة:\n{list}",
        "blacklist_words": "أرسل كلمات القائمة السوداء (مفصولة بفواصل):",
        "whitelist_words": "أرسل كلمات القائمة البيضاء (مفصولة بفواصل):",
        "filter_added": "تم تعيين الفلتر لـ {channel}!",
        "message_format": "اختر تنسيق الرسالة:\n1. النص فقط\n2. النص + قناة المصدر",
        "format_set": "تم تعيين تنسيق الرسالة إلى '{format}'!",
        "back": "رجوع",
        "stop_options": ["شخصي", "عام", "رجوع"],
        "error_numeric_id": "المعرف يجب أن يكون رقميًا!",
        "error_invalid_format": "صيغة خاطئة! مثل 'ID ترقية' أو 'ID تنزيل'",
        "error_invalid_channel": "قناة غير صالحة!",
        "error_invalid_lang": "فقط fa، en، ar، ru!",
        "error_invalid_format_choice": "فقط 1 أو 2!",
        "monitor_error": "خطا في مراقبة القناة {channel}: {error}",
        "invite_link_prompt": "أرسل رابط الدعوة للقناة الخاصة (أو اكتب 'تخطي' للتخطي):",
        "invite_link_saved": "تم حفظ رابط الدعوة!",
        "channel_skipped": "تم تخطي القناة."
    },
    "ru": {
        "main_menu": ["Управление админами", "Управление каналами", "Перевод текста", "Остановить бота", "Настройки"],
        "welcome": "Добро пожаловать! Выберите из меню:",
        "creator_init": "Отправьте пароль для регистрации как Создатель:",
        "creator_success": "Вы зарегистрированы как Создатель!",
        "not_admin": "Вы не администратор!",
        "chat_destination": "Отправьте ID целевого чата (например, @username или числовой ID):",
        "admins_menu": ["Список админов", "Добавить админа", "Удалить админа", "Повысить/понизить админа", "Назад"],
        "channels_menu": ["Список каналов", "Добавить канал", "Удалить канал", "Черный список", "Фильтры слов", "Пригласительная ссылка для частного канала", "Пропустить канал", "Назад"],
        "admin_list": "Список админов:\n{list}",
        "add_admin_prompt": "На каком уровне? Мастер-админ, Супер-админ или Админ:",
        "add_admin_id": "Отправьте числовой ID админа:",
        "admin_added": "Админ {user_id} добавлен на уровень {level}!",
        "remove_admin_id": "Отправьте ID админа:",
        "admin_removed": "Админ {user_id} удален!",
        "promote_demote": "Выберите админа:\n{list}\nЗатем скажите 'Повысить' или 'Понизить':",
        "level_changed": "Уровень {user_id} изменен на {level}!",
        "channels_list": "Ваши каналы:\n{list}",
        "add_channel_prompt": "Отправьте ID канала или пересланное сообщение:",
        "channel_added": "Канал успешно добавлен!",
        "remove_channel_prompt": "Отправьте ID канала:",
        "channel_removed": "Канал удален!",
        "blacklist_prompt": "ID канала для черного списка:",
        "blacklist_added": "Канал добавлен в черный список!",
        "blacklist_error": "Этот канал в черном списке!",
        "limit_exceeded": "Максимальное количество каналов для вашего уровня: {limit}",
        "translate_prompt": "Отправьте текст:",
        "stop_personal": "Бот остановлен для вас!",
        "stop_global": "Бот остановлен для всех!",
        "settings_menu": ["Язык интерфейса", "Язык перевода", "Изменить целевой чат", "Формат сообщения", "Назад"],
        "interface_lang": "Выберите язык интерфейса (fa, en, ar, ru):",
        "dest_lang": "Выберите язык перевода (например, en или fr):",
        "no_access": "У вас нет доступа к этому!",
        "capacity_increased": "Ваша емкость мониторинга каналов увеличена до {limit}!",
        "channels_adjusted": "Из-за понижения уровня {count} последних каналов удалены из вашего списка.",
        "filter_menu": ["Черный список слов", "Белый список слов", "Назад"],
        "select_channel": "Выберите канал:\n{list}",
        "blacklist_words": "Отправьте слова черного списка (через запятую):",
        "whitelist_words": "Отправьте слова белого списка (через запятую):",
        "filter_added": "Фильтр установлен для {channel}!",
        "message_format": "Выберите формат сообщения:\n1. Только текст\n2. Текст + канал-источник",
        "format_set": "Формат сообщения установлен на '{format}'!",
        "back": "Назад",
        "stop_options": ["Лично", "Глобально", "Назад"],
        "error_numeric_id": "ID должен быть числовым!",
        "error_invalid_format": "Неверный формат! Например, 'ID Повысить' или 'ID Понизить'",
        "error_invalid_channel": "Недействительный канал!",
        "error_invalid_lang": "Только fa, en, ar, ru!",
        "error_invalid_format_choice": "Только 1 или 2!",
        "monitor_error": "Ошибка мониторинга канала {channel}: {error}",
        "invite_link_prompt": "Отправьте пригласительную ссылку для частного канала (или напишите 'Пропустить' для пропуска):",
        "invite_link_saved": "Пригласительная ссылка сохранена!",
        "channel_skipped": "Канал пропущен."
    }
}
